
Vagrant.configure("2") do |config|

	config.vm.box = "centos/7"

	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 1
		vb.memory = 1024
		# vb.ssh_private_key_path = "insecure_private_key"
	end

	config.vm.provision "shell" do |s|
			s.path="common.sh"
		end

	config.vm.define "hadoop" do |hadoop|
		hadoop.vm.hostname = "hadoop.com"
		hadoop.vm.network "private_network", ip: "192.168.100.10"

		hadoop.vm.provision "puppet"

		config.vm.provision "shell" do |s|
			s.path = "hadoop.sh"
		end
  		
	end

	# config.vm.define "sqoop" do |sqoop|
	# 	sqoop.vm.hostname = "sqoop.com"
	# 	sqoop.vm.network "private_network", ip: "192.168.100.11"
	# 	config.vm.provision "shell", path: "sqoop.sh"
	# end

end