management:
  endpoint:
    beans:
      enabled: true
    web:
      exposure:
        include: beans
spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:/schema-h2.sql
#      initializer:
#        enabled: true
  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.jdbc.datasource.init: debug
